WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

START_WIDTH = (WINDOW_WIDTH - 64 * 5) / 2 - 10
START_HEIGHT = (WINDOW_HEIGHT - 64 * 5) / 2

ANIMATION_SPEED = 0.8

PLAYER_SIDE = 64

PLAYER_WIDTH = PLAYER_SIDE
PLAYER_HEIGHT = PLAYER_SIDE


