-- Globals
CIRCLE = math.pi * 2

-- Window Scope
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

-- Interface Scope
HEADER_HEIGHT = 40
TEXT_HEIGHT = 12

PADDING = 20

-- Game Area
GAME_WIDTH = WINDOW_WIDTH - PADDING * 2
GAME_HEIGHT = WINDOW_HEIGHT - PADDING * 2 - HEADER_HEIGHT

GAME_PADDING_TOP = PADDING + HEADER_HEIGHT
GAME_PADDING_BOTTOM = PADDING
GAME_PADDING_LEFT = PADDING
GAME_PADDING_RIGHT = PADDING

-- Cells
CELL_SIDE = 40

CELL_NUMBER = 50

-- Entity Constants
ENTITY_SITUATION_TURNING = 0
ENTITY_SITUATION_RUNNING = 1
ENTITY_SITUATION_FOLLOWING = 2

-- Entity Caracteristics
ENTITY_RADIUS = 10

ENTITY_MAX_SPEED = 5
ENTITY_ACCELERATION = 0.4

-- Game Config
ENEMY_NUMBER = 15

-- Rebound areas
TOP_REBOUND = GAME_PADDING_TOP + ENTITY_RADIUS
BOTTOM_REBOUND = GAME_PADDING_TOP + GAME_HEIGHT - ENTITY_RADIUS
LEFT_REBOUND = GAME_PADDING_LEFT + ENTITY_RADIUS
RIGHT_REBOUND = GAME_PADDING_LEFT + GAME_WIDTH - ENTITY_RADIUS

-- Checking if there is problems
if GAME_WIDTH < 400 or GAME_HEIGHT < 400 then
	print('Game window too small')
	os.exit()
end

if GAME_WIDTH % CELL_SIDE ~= 0 or GAME_HEIGHT % CELL_SIDE ~= 0 then
	print('Game width (' .. GAME_WIDTH .. ') and height (' .. GAME_HEIGHT .. ') must be divisible by cell side length: ' .. CELL_SIDE)
	os.exit()
end
